name: refrigerator_alchemist
description: Turn your fridge into recipes with AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  image: ^4.1.3
  image_picker: ^1.0.7
  screenshot: ^3.0.0  # Add this
  share_plus: ^10.0.0 # Add this
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  
  # Firebase (Auth + Database)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.0
  
  # Ads
  google_mobile_ads: ^5.1.0
  
  # Camera & Networking
  camera: ^0.11.0+2
  http: ^1.2.0
  flutter_dotenv: ^5.2.1
  
  # UI & Typography
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Tool to generate App Icons
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - lib/assets/  # <--- Changed this to match your folder location

# *** ICON CONFIGURATION ***
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/assets/logo.png" # <--- Pointing to the file inside lib
  min_sdk_android: 23